"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import tempfile
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _read_fail_closed_bool(name: str, *, default: bool = False) -> bool:
    raw_value = os.getenv(name)
    if raw_value is None:
        return default

    normalized_value = raw_value.strip().casefold()
    if normalized_value in {"1", "true", "yes", "on"}:
        return True
    if normalized_value in {"0", "false", "no", "off"}:
        return False

    return False


def _paths_overlap(first: Path, second: Path) -> bool:
    return (
        first == second
        or first.is_relative_to(second)
        or second.is_relative_to(first)
    )


def _read_image_storage_root(
    name: str,
    *,
    default: Path,
    required: bool = False,
) -> Path:
    raw_value = os.getenv(name)
    if raw_value is None:
        if required:
            raise ImproperlyConfigured(
                f"{name} must be set when image assets are enabled outside debug"
            )
        candidate = default
    else:
        if not raw_value.strip():
            raise ImproperlyConfigured(f"{name} cannot be empty")
        candidate = Path(raw_value).expanduser()

    if not candidate.is_absolute():
        raise ImproperlyConfigured(f"{name} must be an absolute path")

    normalized_candidate = candidate.resolve(strict=False)
    if normalized_candidate == Path(normalized_candidate.anchor):
        raise ImproperlyConfigured(f"{name} cannot be the filesystem root")

    return normalized_candidate


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"

IMAGE_ASSET_FEATURE_ENABLED = _read_fail_closed_bool(
    "IMAGE_ASSET_FEATURE_ENABLED",
    default=False,
)
BRAVE_IMAGE_SEARCH_API_KEY = os.getenv("BRAVE_IMAGE_SEARCH_API_KEY", "").strip()

# --- Production security settings ---
if not DEBUG:
    # Force HTTPS
    SECURE_SSL_REDIRECT = True

    # Cookies only over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS (start low, increase later when you're confident)
    SECURE_HSTS_SECONDS = 60  # start with 1 minute
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

    # If you are behind a reverse proxy (nginx/traefik)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

ALLOWED_HOSTS = (
    [host.strip() for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if host.strip()]
    if not DEBUG
    else ["*"]
)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "crm",
    "drf_spectacular",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "crm_db"),
        "USER": os.getenv("DB_USER", "crm"),
        "PASSWORD": os.getenv("DB_PASSWORD", "crm_password"),
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

_LOCAL_IMAGE_STORAGE_ROOT = (
    Path(tempfile.gettempdir()).resolve(strict=False) / "kreative-norge-crm-media"
)
IMAGE_ORIGINALS_ROOT = _read_image_storage_root(
    "IMAGE_ORIGINALS_ROOT",
    default=_LOCAL_IMAGE_STORAGE_ROOT / "originals-private",
    required=not DEBUG and IMAGE_ASSET_FEATURE_ENABLED,
)
IMAGE_RENDITIONS_ROOT = _read_image_storage_root(
    "IMAGE_RENDITIONS_ROOT",
    default=_LOCAL_IMAGE_STORAGE_ROOT / "renditions-public",
    required=not DEBUG and IMAGE_ASSET_FEATURE_ENABLED,
)

_NORMALIZED_BASE_DIR = BASE_DIR.resolve(strict=False)
_NORMALIZED_STATIC_ROOT = STATIC_ROOT.resolve(strict=False)

for _setting_name, _storage_root in (
    ("IMAGE_ORIGINALS_ROOT", IMAGE_ORIGINALS_ROOT),
    ("IMAGE_RENDITIONS_ROOT", IMAGE_RENDITIONS_ROOT),
):
    if _paths_overlap(_storage_root, _NORMALIZED_STATIC_ROOT):
        raise ImproperlyConfigured(
            f"{_setting_name} cannot overlap STATIC_ROOT"
        )
    if _paths_overlap(_storage_root, _NORMALIZED_BASE_DIR):
        raise ImproperlyConfigured(
            f"{_setting_name} must be outside the application repository"
        )

if _paths_overlap(IMAGE_ORIGINALS_ROOT, IMAGE_RENDITIONS_ROOT):
    raise ImproperlyConfigured(
        "IMAGE_ORIGINALS_ROOT and IMAGE_RENDITIONS_ROOT cannot overlap"
    )

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "image_originals_private": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": IMAGE_ORIGINALS_ROOT,
            "base_url": None,
        },
    },
    "image_renditions_public": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": IMAGE_RENDITIONS_ROOT,
            "base_url": None,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework / OpenAPI schema
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/min",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Kreative Norge 2.0 API",
    "DESCRIPTION": "Internt CRM API (tenant-basert) + Public API for aktørsider.",
    "VERSION": "0.1.0",
}


OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "").strip()
OPENAI_IMPORT_ENABLED = os.getenv("OPENAI_IMPORT_ENABLED", "True").lower() == "true"
OPENAI_IMPORT_MODEL = os.getenv("OPENAI_IMPORT_MODEL", "gpt-5.4").strip() or "gpt-5.4"
OPENAI_IMPORT_TIMEOUT = float(os.getenv("OPENAI_IMPORT_TIMEOUT", "20"))
