# Generated by Django 5.1.15 on 2025-12-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='municipalities',
            field=models.CharField(blank=True, help_text='Kommune(r), f.eks. Bodø eller Bodø, Tromsø', max_length=255),
        ),
    ]
