# Generated by Django 5.1.15 on 2026-03-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_organization_facebook_url_organization_instagram_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="tiktok_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="instagram_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="tiktok_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
