# Generated by Django 5.1.15 on 2026-03-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_organization_description'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subcategory',
            new_name='crm_subcate_categor_829f2b_idx',
            old_name='crm_subcate_categor_1c5e10_idx',
        ),
        migrations.RenameIndex(
            model_name='subcategory',
            new_name='crm_subcate_categor_9ef581_idx',
            old_name='crm_subcate_categor_91c48a_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='crm_tag_tenant__5ca806_idx',
            old_name='crm_tag_tenant__013be9_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='crm_tag_tenant__8467db_idx',
            old_name='crm_tag_tenant__1c474d_idx',
        ),
    ]
