# Generated by Django 5.1.15 on 2026-04-03 12:38

import crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_person_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'XLSX'), ('GOOGLE_SHEET', 'Google Sheet'), ('CHECKIN', 'Checkin'), ('MAILMOJO', 'Mailmojo'), ('MANUAL_API', 'Manual API')], max_length=32)),
                ('import_mode', models.CharField(choices=[('COMBINED', 'Combined'), ('ORGANIZATIONS_ONLY', 'Organizations only'), ('PEOPLE_ONLY', 'People only')], max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UPLOADED', 'Uploaded'), ('PARSED', 'Parsed'), ('PREVIEW_READY', 'Preview ready'), ('AWAITING_REVIEW', 'Awaiting review'), ('COMMITTING', 'Committing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=crm.models.import_job_upload_to)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('preview_report_file', models.FileField(blank=True, null=True, upload_to=crm.models.import_job_report_upload_to)),
                ('error_report_file', models.FileField(blank=True, null=True, upload_to=crm.models.import_job_report_upload_to)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_import_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='crm.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_payload_json', models.JSONField(blank=True, default=dict)),
                ('normalized_payload_json', models.JSONField(blank=True, default=dict)),
                ('detected_entities_json', models.JSONField(blank=True, default=dict)),
                ('match_result_json', models.JSONField(blank=True, default=dict)),
                ('ai_suggestions_json', models.JSONField(blank=True, default=dict)),
                ('validation_errors_json', models.JSONField(blank=True, default=list)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('row_status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('REVIEW_REQUIRED', 'Review required'), ('SKIPPED', 'Skipped'), ('COMMITTED', 'Committed'), ('COMMIT_FAILED', 'Commit failed')], default='REVIEW_REQUIRED', max_length=32)),
                ('proposed_action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('LINK_ONLY', 'Link only'), ('SKIP', 'Skip')], default='SKIP', max_length=32)),
                ('decision_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='crm.importjob')),
            ],
            options={
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImportDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('USE_EXISTING_ORGANIZATION', 'Use existing organization'), ('CREATE_NEW_ORGANIZATION', 'Create new organization'), ('USE_EXISTING_PERSON', 'Use existing person'), ('CREATE_NEW_PERSON', 'Create new person'), ('MAP_CATEGORY', 'Map category'), ('MAP_SUBCATEGORY', 'Map subcategory'), ('ACCEPT_NEW_TAG', 'Accept new tag'), ('SKIP_ROW', 'Skip row')], max_length=48)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_decisions', to=settings.AUTH_USER_MODEL)),
                ('import_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='crm.importrow')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImportCommitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('PERSON', 'Person'), ('PERSON_CONTACT', 'Person contact'), ('ORGANIZATION_PERSON', 'Organization person'), ('TAG', 'Tag')], max_length=32)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('LINKED', 'Linked'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], max_length=16)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_logs', to='crm.importjob')),
                ('import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commit_logs', to='crm.importrow')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('SEARCH_RESULTS', 'Search results'), ('ADMIN_FULL', 'Admin full'), ('PERSONS_ONLY', 'Persons only'), ('ORGANIZATIONS_ONLY', 'Organizations only')], max_length=32)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'XLSX')], max_length=8)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('selected_fields_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to=crm.models.export_job_upload_to)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_export_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='crm.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='crm_exportj_tenant__8c36da_idx'), models.Index(fields=['tenant', 'created_at'], name='crm_exportj_tenant__910108_idx'), models.Index(fields=['tenant', 'export_type'], name='crm_exportj_tenant__ab27cf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['tenant', 'status'], name='crm_importj_tenant__659c18_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['tenant', 'created_at'], name='crm_importj_tenant__0f7507_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['tenant', 'source_type'], name='crm_importj_tenant__ef7553_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['import_job', 'row_status'], name='crm_importr_import__dc9519_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['import_job', 'proposed_action'], name='crm_importr_import__3b6a98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importrow',
            unique_together={('import_job', 'row_number')},
        ),
        migrations.AddIndex(
            model_name='importdecision',
            index=models.Index(fields=['import_row', 'decision_type'], name='crm_importd_import__5b5ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='importcommitlog',
            index=models.Index(fields=['import_job', 'action'], name='crm_importc_import__d8d430_idx'),
        ),
        migrations.AddIndex(
            model_name='importcommitlog',
            index=models.Index(fields=['import_job', 'entity_type'], name='crm_importc_import__62a4c0_idx'),
        ),
    ]
