# Generated by Django 5.1.15 on 2026-04-03 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_importdecision_ai_suggestion_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('gruppeadmin', 'Gruppeadmin'), ('redigerer', 'Redigerer'), ('leser', 'Leser')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='crm.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant__name', 'user__username'],
                'indexes': [models.Index(fields=['tenant', 'role'], name='crm_tenantm_tenant__c0c199_idx'), models.Index(fields=['user', 'role'], name='crm_tenantm_user_id_2bab5a_idx')],
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
