# Generated by Django 5.1.15 on 2026-08-03 19:58

import crm.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_tenantmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_storage_key', models.CharField(max_length=1024, validators=[crm.validators.validate_storage_key])),
                ('checksum_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(code='invalid_sha256', message='Enter a lowercase hexadecimal SHA-256 checksum.', regex='^[0-9a-f]{64}$')])),
                ('original_format', models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WebP')], max_length=8)),
                ('mime_type', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('validation_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to='crm.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ImageRenditionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_mode', models.CharField(choices=[('cover', 'Cover'), ('contain', 'Contain')], max_length=8)),
                ('focus_x', models.DecimalField(decimal_places=4, default=Decimal('0.5000'), max_digits=5)),
                ('focus_y', models.DecimalField(decimal_places=4, default=Decimal('0.5000'), max_digits=5)),
                ('processing_version', models.CharField(max_length=64)),
                ('render_config_hash_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(code='invalid_sha256', message='Enter a lowercase hexadecimal SHA-256 checksum.', regex='^[0-9a-f]{64}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendition_sets', to='crm.imageasset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_rendition_sets', to='crm.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ImageRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('square', 'Square'), ('landscape', 'Landscape'), ('share', 'Share')], max_length=12)),
                ('output_format', models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WebP')], max_length=8)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(code='invalid_sha256', message='Enter a lowercase hexadecimal SHA-256 checksum.', regex='^[0-9a-f]{64}$')])),
                ('artifact_storage_key', models.CharField(max_length=1024, validators=[crm.validators.validate_storage_key])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_renditions', to='crm.tenant')),
                ('rendition_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renditions', to='crm.imagerenditionset')),
            ],
        ),
        migrations.AddConstraint(
            model_name='imageasset',
            constraint=models.UniqueConstraint(fields=('tenant', 'private_storage_key'), name='image_asset_tenant_private_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='imageasset',
            constraint=models.CheckConstraint(condition=models.Q(('width__gt', 0)), name='image_asset_width_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='imageasset',
            constraint=models.CheckConstraint(condition=models.Q(('height__gt', 0)), name='image_asset_height_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='imageasset',
            constraint=models.CheckConstraint(condition=models.Q(('file_size_bytes__gt', 0)), name='image_asset_size_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='imagerenditionset',
            constraint=models.UniqueConstraint(fields=('tenant', 'asset', 'render_config_hash_sha256'), name='image_rset_tenant_asset_hash_uniq'),
        ),
        migrations.AddConstraint(
            model_name='imagerenditionset',
            constraint=models.CheckConstraint(condition=models.Q(('focus_x__gte', 0), ('focus_x__lte', 1)), name='image_rset_focus_x_range'),
        ),
        migrations.AddConstraint(
            model_name='imagerenditionset',
            constraint=models.CheckConstraint(condition=models.Q(('focus_y__gte', 0), ('focus_y__lte', 1)), name='image_rset_focus_y_range'),
        ),
        migrations.AddConstraint(
            model_name='imagerendition',
            constraint=models.UniqueConstraint(fields=('tenant', 'rendition_set', 'variant'), name='image_rend_tenant_set_variant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='imagerendition',
            constraint=models.UniqueConstraint(fields=('tenant', 'artifact_storage_key'), name='image_rend_tenant_artifact_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='imagerendition',
            constraint=models.CheckConstraint(condition=models.Q(('width__gt', 0)), name='image_rend_width_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='imagerendition',
            constraint=models.CheckConstraint(condition=models.Q(('height__gt', 0)), name='image_rend_height_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='imagerendition',
            constraint=models.CheckConstraint(condition=models.Q(('file_size_bytes__gt', 0)), name='image_rend_size_gt_0'),
        ),
    ]
