# Generated by Django 5.1.15 on 2026-08-03 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_image_domain_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationImageSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_kind', models.CharField(choices=[('asset', 'Asset'), ('system_fallback', 'System fallback')], max_length=20)),
                ('alt_text', models.CharField(max_length=500)),
                ('public_credit', models.CharField(blank=True, default='', max_length=500)),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], max_length=8)),
                ('locked_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locked_organization_image_selections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_selections', to='crm.organization')),
                ('rendition_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_selections', to='crm.imagerenditionset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_image_selections', to='crm.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'organization', 'revision'), name='img_sel_tenant_org_rev_uniq'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant', 'organization'), name='img_sel_one_active_per_org'), models.CheckConstraint(condition=models.Q(('revision__gt', 0)), name='img_sel_revision_gt_0'), models.CheckConstraint(condition=models.Q(models.Q(('rendition_set__isnull', False), ('selection_kind', 'asset')), models.Q(('rendition_set__isnull', True), ('selection_kind', 'system_fallback')), _connector='OR'), name='img_sel_kind_rset_xor'), models.CheckConstraint(condition=models.Q(('alt_text', ''), _negated=True), name='img_sel_alt_text_not_empty')],
            },
        ),
    ]
