# Generated by Django 5.1.15 on 2026-04-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_internaltag_and_assignments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='internaltag',
            new_name='crm_interna_tenant__605165_idx',
            old_name='crm_internt_tenant__f8fd65_idx',
        ),
        migrations.RenameIndex(
            model_name='internaltag',
            new_name='crm_interna_tenant__a9a41c_idx',
            old_name='crm_internt_tenant__d46dfb_idx',
        ),
    ]
