# Generated by Django 5.1.15 on 2026-08-03 21:18

import crm.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0022_organization_image_selection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageReviewEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("selection_locked", "Selection locked"), ("selection_replaced", "Selection replaced")], max_length=24)),
                ("organization_id_snapshot", models.PositiveBigIntegerField()),
                ("organization_name_snapshot", models.CharField(max_length=255)),
                ("organization_org_number_snapshot", models.CharField(blank=True, default="", max_length=32)),
                ("selection_id_snapshot", models.PositiveBigIntegerField()),
                ("selection_revision_snapshot", models.PositiveIntegerField()),
                ("selection_kind_snapshot", models.CharField(choices=[("asset", "Asset"), ("system_fallback", "System fallback")], max_length=20)),
                ("rendition_set_id_snapshot", models.PositiveBigIntegerField(blank=True, null=True)),
                ("asset_id_snapshot", models.PositiveBigIntegerField(blank=True, null=True)),
                ("asset_checksum_sha256_snapshot", models.CharField(blank=True, default="", max_length=64, validators=[django.core.validators.RegexValidator(code="invalid_sha256", message="Enter a lowercase hexadecimal SHA-256 checksum.", regex="^[0-9a-f]{64}$")])),
                ("asset_validation_version_snapshot", models.CharField(blank=True, default="", max_length=64)),
                ("previous_selection_id_snapshot", models.PositiveBigIntegerField(blank=True, null=True)),
                ("previous_selection_revision_snapshot", models.PositiveIntegerField(blank=True, null=True)),
                ("actor_user_id_snapshot", models.PositiveBigIntegerField()),
                ("actor_username_snapshot", models.CharField(max_length=255)),
                ("alt_text_snapshot", models.CharField(max_length=500)),
                ("public_credit_snapshot", models.CharField(blank=True, default="", max_length=500)),
                ("source_type_snapshot", models.CharField(blank=True, choices=[("official_website", "Official website"), ("open_graph", "Open Graph"), ("website_image", "Website image"), ("brave_image_search", "Brave image search"), ("upload", "Upload"), ("pasted_url", "Pasted URL")], default="", max_length=32)),
                ("source_url_snapshot", models.URLField(blank=True, default="", max_length=2048)),
                ("source_page_url_snapshot", models.URLField(blank=True, default="", max_length=2048)),
                ("provider_snapshot", models.CharField(blank=True, default="", max_length=255)),
                ("technical_warnings_snapshot", models.JSONField(blank=True, default=list, validators=[crm.models.validate_technical_warnings])),
                ("approval_text_version_snapshot", models.CharField(blank=True, default="", max_length=64)),
                ("approval_text_snapshot", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField()),
                ("actor_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="image_review_events", to=settings.AUTH_USER_MODEL)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="review_events", to="crm.imageasset")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="image_review_events", to="crm.organization")),
                ("previous_selection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="replacement_events", to="crm.organizationimageselection")),
                ("rendition_set", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="review_events", to="crm.imagerenditionset")),
                ("selection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="review_events", to="crm.organizationimageselection")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="image_review_events", to="crm.tenant")),
            ],
            options={
                "base_manager_name": "_base_objects",
                "default_manager_name": "objects",
                "indexes": [models.Index(fields=["tenant", "organization_id_snapshot", "created_at"], name="img_evt_tenant_org_time_idx")],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("actor_user_id_snapshot__gt", 0), ("organization_id_snapshot__gt", 0), ("selection_id_snapshot__gt", 0), ("selection_revision_snapshot__gt", 0)), name="img_evt_required_ids_gt_0"),
                    models.CheckConstraint(condition=models.Q(models.Q(("event_type", "selection_locked"), ("previous_selection_id_snapshot__isnull", True), ("previous_selection_revision_snapshot__isnull", True)), models.Q(("event_type", "selection_replaced"), ("previous_selection_id_snapshot__gt", 0), ("previous_selection_id_snapshot__isnull", False), ("previous_selection_revision_snapshot__gt", 0), ("previous_selection_revision_snapshot__isnull", False)), _connector="OR"), name="img_evt_previous_contract"),
                    models.CheckConstraint(condition=models.Q(models.Q(("asset_id_snapshot__gt", 0), ("asset_id_snapshot__isnull", False), ("rendition_set_id_snapshot__gt", 0), ("rendition_set_id_snapshot__isnull", False), ("selection_kind_snapshot", "asset"), models.Q(("asset_checksum_sha256_snapshot", ""), _negated=True), models.Q(("asset_validation_version_snapshot", ""), _negated=True), models.Q(("source_type_snapshot", ""), _negated=True), models.Q(("approval_text_version_snapshot", ""), _negated=True), models.Q(("approval_text_snapshot", ""), _negated=True)), models.Q(("approval_text_snapshot", ""), ("approval_text_version_snapshot", ""), ("asset_checksum_sha256_snapshot", ""), ("asset_id_snapshot__isnull", True), ("asset_validation_version_snapshot", ""), ("provider_snapshot", ""), ("rendition_set_id_snapshot__isnull", True), ("selection_kind_snapshot", "system_fallback"), ("source_page_url_snapshot", ""), ("source_type_snapshot", ""), ("source_url_snapshot", ""), ("technical_warnings_snapshot", [])), _connector="OR"), name="img_evt_selection_kind_contract"),
                    models.CheckConstraint(condition=models.Q(("source_type_snapshot", ""), ("source_type_snapshot__in", ["official_website", "open_graph", "website_image", "brave_image_search", "upload", "pasted_url"]), _connector="OR"), name="img_evt_source_type_valid"),
                    models.CheckConstraint(condition=models.Q(models.Q(("source_type_snapshot", ""), ("source_url_snapshot", "")), ("source_type_snapshot", "upload"), models.Q(("source_url_snapshot", ""), _negated=True), _connector="OR"), name="img_evt_source_url_contract"),
                    models.CheckConstraint(condition=models.Q(models.Q(("organization_name_snapshot", ""), _negated=True), models.Q(("actor_username_snapshot", ""), _negated=True), models.Q(("alt_text_snapshot", ""), _negated=True)), name="img_evt_required_text_not_empty"),
                ],
            },
            managers=[
                ("_base_objects", django.db.models.manager.Manager()),
                ("objects", crm.models.ImageReviewEventManager()),
            ],
        ),
    ]
