# Generated by Django 5.1.15 on 2026-08-05 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0023_imagereviewevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="imagereviewevent",
            name="img_evt_previous_contract",
        ),
        migrations.AlterField(
            model_name="imagereviewevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("selection_locked", "Selection locked"),
                    ("selection_replaced", "Selection replaced"),
                    (
                        "selection_removed_to_fallback",
                        "Selection removed to fallback",
                    ),
                ],
                max_length=29,
            ),
        ),
        migrations.AddConstraint(
            model_name="imagereviewevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event_type", "selection_locked"),
                        ("previous_selection_id_snapshot__isnull", True),
                        ("previous_selection_revision_snapshot__isnull", True),
                    ),
                    models.Q(
                        ("event_type", "selection_replaced"),
                        ("previous_selection_id_snapshot__gt", 0),
                        ("previous_selection_id_snapshot__isnull", False),
                        ("previous_selection_revision_snapshot__gt", 0),
                        ("previous_selection_revision_snapshot__isnull", False),
                    ),
                    models.Q(
                        ("event_type", "selection_removed_to_fallback"),
                        ("previous_selection_id_snapshot__gt", 0),
                        ("previous_selection_id_snapshot__isnull", False),
                        ("previous_selection_revision_snapshot__gt", 0),
                        ("previous_selection_revision_snapshot__isnull", False),
                        ("selection_kind_snapshot", "system_fallback"),
                    ),
                    _connector="OR",
                ),
                name="img_evt_previous_contract",
            ),
        ),
    ]
