# Generated by Django 5.1.15 on 2026-08-05 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_remove_imagereviewevent_img_evt_previous_contract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imagereviewevent',
            name='img_evt_selection_kind_contract',
        ),
        migrations.RemoveConstraint(
            model_name='imagereviewevent',
            name='img_evt_previous_contract',
        ),
        migrations.AddField(
            model_name='imagereviewevent',
            name='restored_from_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_events', to='crm.organizationimageselection'),
        ),
        migrations.AddField(
            model_name='imagereviewevent',
            name='restored_from_selection_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagereviewevent',
            name='restored_from_selection_revision_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagereviewevent',
            name='event_type',
            field=models.CharField(choices=[('selection_locked', 'Selection locked'), ('selection_replaced', 'Selection replaced'), ('selection_removed_to_fallback', 'Selection removed to fallback'), ('selection_restored', 'Selection restored')], max_length=29),
        ),
        migrations.AddConstraint(
            model_name='imagereviewevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'selection_locked'), ('previous_selection_id_snapshot__isnull', True), ('previous_selection_revision_snapshot__isnull', True)), models.Q(('event_type', 'selection_replaced'), ('previous_selection_id_snapshot__gt', 0), ('previous_selection_id_snapshot__isnull', False), ('previous_selection_revision_snapshot__gt', 0), ('previous_selection_revision_snapshot__isnull', False)), models.Q(('event_type', 'selection_removed_to_fallback'), ('previous_selection_id_snapshot__gt', 0), ('previous_selection_id_snapshot__isnull', False), ('previous_selection_revision_snapshot__gt', 0), ('previous_selection_revision_snapshot__isnull', False), ('selection_kind_snapshot', 'system_fallback')), models.Q(('event_type', 'selection_restored'), ('previous_selection_id_snapshot__gt', 0), ('previous_selection_id_snapshot__isnull', False), ('previous_selection_revision_snapshot__gt', 0), ('previous_selection_revision_snapshot__isnull', False)), _connector='OR'), name='img_evt_previous_contract'),
        ),
        migrations.AddConstraint(
            model_name='imagereviewevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset_id_snapshot__gt', 0), ('asset_id_snapshot__isnull', False), ('event_type__in', ['selection_locked', 'selection_replaced']), ('rendition_set_id_snapshot__gt', 0), ('rendition_set_id_snapshot__isnull', False), ('selection_kind_snapshot', 'asset'), models.Q(('asset_checksum_sha256_snapshot', ''), _negated=True), models.Q(('asset_validation_version_snapshot', ''), _negated=True), models.Q(('source_type_snapshot', ''), _negated=True), models.Q(('approval_text_version_snapshot', ''), _negated=True), models.Q(('approval_text_snapshot', ''), _negated=True)), models.Q(('approval_text_snapshot', ''), ('approval_text_version_snapshot', ''), ('asset_id_snapshot__gt', 0), ('asset_id_snapshot__isnull', False), ('event_type', 'selection_restored'), ('provider_snapshot', ''), ('rendition_set_id_snapshot__gt', 0), ('rendition_set_id_snapshot__isnull', False), ('selection_kind_snapshot', 'asset'), ('source_page_url_snapshot', ''), ('source_type_snapshot', ''), ('source_url_snapshot', ''), ('technical_warnings_snapshot', []), models.Q(('asset_checksum_sha256_snapshot', ''), _negated=True), models.Q(('asset_validation_version_snapshot', ''), _negated=True)), models.Q(('approval_text_snapshot', ''), ('approval_text_version_snapshot', ''), ('asset_checksum_sha256_snapshot', ''), ('asset_id_snapshot__isnull', True), ('asset_validation_version_snapshot', ''), ('provider_snapshot', ''), ('rendition_set_id_snapshot__isnull', True), ('selection_kind_snapshot', 'system_fallback'), ('source_page_url_snapshot', ''), ('source_type_snapshot', ''), ('source_url_snapshot', ''), ('technical_warnings_snapshot', [])), _connector='OR'), name='img_evt_selection_kind_contract'),
        ),
        migrations.AddConstraint(
            model_name='imagereviewevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'selection_restored'), ('restored_from_selection_id_snapshot__gt', 0), ('restored_from_selection_id_snapshot__isnull', False), ('restored_from_selection_revision_snapshot__gt', 0), ('restored_from_selection_revision_snapshot__isnull', False), ('selection_kind_snapshot', 'asset')), models.Q(models.Q(('event_type', 'selection_restored'), _negated=True), ('restored_from_selection_id_snapshot__isnull', True), ('restored_from_selection_revision_snapshot__isnull', True)), _connector='OR'), name='img_evt_restore_contract'),
        ),
    ]
