# Generated by Django 5.1.15 on 2026-08-07 20:33

import crm.models
import crm.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_restore_archived_image_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationImageRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.UUIDField(editable=False, unique=True)),
                ('key_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_releases', to='crm.organization')),
                ('rendition_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_image_releases', to='crm.imagerenditionset')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_releases', to='crm.organizationimageselection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_image_releases', to='crm.tenant')),
            ],
            options={
                'base_manager_name': '_base_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('_base_objects', crm.models.ImmutableImageReleaseManager()),
                ('objects', crm.models.ImmutableImageReleaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationImageReleaseRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('square', 'Square'), ('landscape', 'Landscape'), ('share', 'Share')], max_length=12)),
                ('output_format', models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WebP')], max_length=8)),
                ('artifact_storage_key_snapshot', models.CharField(max_length=1024, validators=[crm.validators.validate_storage_key])),
                ('artifact_checksum_sha256_snapshot', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(code='invalid_sha256', message='Enter a lowercase hexadecimal SHA-256 checksum.', regex='^[0-9a-f]{64}$')])),
                ('public_storage_key', models.CharField(max_length=1024, unique=True, validators=[crm.validators.validate_storage_key])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renditions', to='crm.organizationimagerelease')),
                ('rendition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_release_mappings', to='crm.imagerendition')),
            ],
            options={
                'base_manager_name': '_base_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('_base_objects', crm.models.ImmutableImageReleaseManager()),
                ('objects', crm.models.ImmutableImageReleaseManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='organizationimagerelease',
            constraint=models.CheckConstraint(condition=models.Q(('key_schema_version', 1)), name='img_release_key_schema_v1'),
        ),
        migrations.AddConstraint(
            model_name='organizationimagereleaserendition',
            constraint=models.UniqueConstraint(fields=('release', 'variant'), name='img_rel_rend_release_variant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='organizationimagereleaserendition',
            constraint=models.UniqueConstraint(fields=('release', 'rendition'), name='img_rel_rend_release_rendition_uniq'),
        ),
        migrations.AddConstraint(
            model_name='organizationimagereleaserendition',
            constraint=models.CheckConstraint(condition=models.Q(('variant__in', ['square', 'landscape', 'share'])), name='img_rel_rend_variant_valid'),
        ),
        migrations.AddConstraint(
            model_name='organizationimagereleaserendition',
            constraint=models.CheckConstraint(condition=models.Q(('output_format__in', ['jpeg', 'png', 'webp'])), name='img_rel_rend_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='organizationimagereleaserendition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artifact_storage_key_snapshot', ''), _negated=True), models.Q(('artifact_checksum_sha256_snapshot', ''), _negated=True), models.Q(('public_storage_key', ''), _negated=True)), name='img_rel_rend_required_text'),
        ),
    ]
