# Generated by Django 5.1.15 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0026_organization_image_release_domain"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="imagereviewevent",
            name="img_evt_source_url_contract",
        ),
        migrations.RemoveConstraint(
            model_name="imagereviewevent",
            name="img_evt_required_text_not_empty",
        ),
        migrations.RemoveConstraint(
            model_name="organizationimageselection",
            name="img_sel_alt_text_not_empty",
        ),
        migrations.AlterField(
            model_name="imagereviewevent",
            name="alt_text_snapshot",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="organizationimageselection",
            name="alt_text",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddConstraint(
            model_name="imagereviewevent",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(source_type_snapshot="", source_url_snapshot="")
                    | models.Q(source_type_snapshot="upload")
                    | models.Q(source_type_snapshot="brave_image_search")
                    | ~models.Q(source_url_snapshot="")
                ),
                name="img_evt_source_url_contract",
            ),
        ),
        migrations.AddConstraint(
            model_name="imagereviewevent",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(organization_name_snapshot="")
                    & ~models.Q(actor_username_snapshot="")
                ),
                name="img_evt_required_text_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationimageselection",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(selection_kind="asset")
                    | ~models.Q(alt_text="")
                ),
                name="img_sel_fallback_alt_required",
            ),
        ),
    ]
