# Generated by Django 5.1.15 on 2026-08-11 07:45

from decimal import Decimal

from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def preserve_non_default_zoom_on_reverse(apps, schema_editor):
    ImageRenditionSet = apps.get_model("crm", "ImageRenditionSet")
    if ImageRenditionSet.objects.exclude(zoom=Decimal("1.0000")).exists():
        raise IrreversibleError(
            "Migration 0028 cannot be reversed after a non-default zoom recipe has been stored."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0027_optional_image_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagerenditionset",
            name="zoom",
            field=models.DecimalField(decimal_places=4, default=Decimal("1.0000"), max_digits=5),
        ),
        migrations.AddConstraint(
            model_name="imagerenditionset",
            constraint=models.CheckConstraint(
                condition=models.Q(("zoom__gte", 1), ("zoom__lte", 3)),
                name="image_rset_zoom_range",
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=preserve_non_default_zoom_on_reverse,
        ),
    ]
