# Generated by Django 5.1.15 on 2026-08-25 21:05

import crm.validators
import django.core.validators
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def preserve_phone_identity_on_reverse(apps, schema_editor):
    Tenant = apps.get_model("crm", "Tenant")
    Organization = apps.get_model("crm", "Organization")
    PersonContact = apps.get_model("crm", "PersonContact")
    if (
        Tenant.objects.filter(default_phone_region__isnull=False).exists()
        or Organization.objects.filter(phone_normalized__isnull=False).exists()
        or Organization.objects.filter(phone_normalization_region__isnull=False).exists()
        or PersonContact.objects.filter(normalized_value__isnull=False).exists()
        or PersonContact.objects.filter(normalization_region__isnull=False).exists()
    ):
        raise IrreversibleError(
            "Migration 0032 cannot be reversed after phone region or normalized "
            "identity data has been stored. Disable callers and preserve the "
            "additive fields instead."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0031_import_image_decision_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="phone_normalization_region",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                validators=[crm.validators.validate_phone_region],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone_normalized",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_e164_phone",
                        message="Enter a canonical E.164 phone number.",
                        regex=r"^\+[1-9][0-9]{1,14}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="personcontact",
            name="normalization_region",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                validators=[crm.validators.validate_phone_region],
            ),
        ),
        migrations.AddField(
            model_name="personcontact",
            name="normalized_value",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_e164_phone",
                        message="Enter a canonical E.164 phone number.",
                        regex=r"^\+[1-9][0-9]{1,14}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="default_phone_region",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                validators=[crm.validators.validate_phone_region],
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["tenant", "phone_normalized"],
                name="org_tenant_phone_norm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personcontact",
            index=models.Index(
                fields=["tenant", "type", "normalized_value"],
                name="pc_tenant_type_phone_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("phone_normalized__isnull", True),
                    ("phone_normalized__regex", r"^\+[1-9][0-9]{1,14}$"),
                    _connector="OR",
                ),
                name="org_phone_normalized_e164",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("phone_normalization_region__isnull", True),
                    ("phone_normalization_region__regex", r"^[A-Z]{2}$"),
                    _connector="OR",
                ),
                name="org_phone_region_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("phone_normalization_region__isnull", True),
                    ("phone_normalized__isnull", False),
                    _connector="OR",
                ),
                name="org_phone_region_requires_norm",
            ),
        ),
        migrations.AddConstraint(
            model_name="personcontact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("normalized_value__isnull", True),
                    ("normalized_value__regex", r"^\+[1-9][0-9]{1,14}$"),
                    _connector="OR",
                ),
                name="pc_normalized_phone_e164",
            ),
        ),
        migrations.AddConstraint(
            model_name="personcontact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("normalization_region__isnull", True),
                    ("normalization_region__regex", r"^[A-Z]{2}$"),
                    _connector="OR",
                ),
                name="pc_phone_region_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="personcontact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("normalization_region__isnull", True),
                    ("normalized_value__isnull", False),
                    _connector="OR",
                ),
                name="pc_phone_region_requires_norm",
            ),
        ),
        migrations.AddConstraint(
            model_name="personcontact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type", "PHONE"),
                    models.Q(
                        ("normalized_value__isnull", True),
                        ("normalization_region__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="pc_phone_identity_fields_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="personcontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("normalized_value__isnull", False)),
                fields=("tenant", "person", "type", "normalized_value"),
                name="pc_person_type_phone_norm_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_phone_region__isnull", True),
                    ("default_phone_region__regex", r"^[A-Z]{2}$"),
                    _connector="OR",
                ),
                name="tenant_phone_region_format",
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=preserve_phone_identity_on_reverse,
        ),
    ]
